import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Menu from '@/components/Menu';
import Providers from '@/Providers';


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex`}>
        <Providers>
          <>
            <div className='w-80 h-screen'>
              <Menu />
            </div>
            <div className='h-screen w-full overflow-auto'>
              {children}
            </div>
          </>
        </Providers>
      </body>
    </html>
  )
}
